name: persist_theme_example
description: Demonstrates how to use the persist_theme plugin.
publish_to: 'none'

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  persist_theme:
    path: ../

flutter:
  uses-material-design: true
