name: persist_theme
description: A flutter plugin for persisting the theme data. Support for Dark Mode.
version: 1.8.0
homepage: https://github.com/fluttercommunity/persist_theme
maintainer: Rody Davis (@rodydavis)

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  flutter_material_color_picker: ^1.1.0+2
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
